from selenium import webdriver
from selenium.webdriver.common.by import By
import time

# Initialize the Chrome WebDriver using WebDriver manager
driver = webdriver.Chrome()
driver.get("https://www.saucedemo.com/")
driver.implicitly_wait(30)
driver.maximize_window()
driver.find_element(By.XPATH, "/html/body/div[1]/div/div[2]/div[1]/div/div/form/div[1]/input").send_keys("standard_user")
time.sleep(5)
driver.find_element(By.XPATH, '/html/body/div[1]/div/div[2]/div[1]/div/div/form/div[2]/input').send_keys("secret_sauce")
time.sleep(5)
driver.find_element(By.XPATH, '/html/body/div[1]/div/div[2]/div[1]/div/div/form/input').click()
time.sleep(5)
driver.find_element(By.XPATH, '/html/body/div[1]/div/div/div[1]/div[1]/div[1]/div/div[1]/div/button').click()
time.sleep(5)
driver.find_element(By.XPATH, '/html/body/div[1]/div/div/div[1]/div[1]/div[1]/div/div[2]/div[1]/nav/a[1]').click()
time.sleep(5)
driver.find_element(By.XPATH, '/html/body/div[1]/div/div/div[1]/div[1]/div[1]/div/div[2]/div[2]/div/button').click()
time.sleep(5)
driver.find_element(By.XPATH, '/html/body/div[1]/div/div/div[2]/div/div/div/div[1]/div[2]/div[2]/button').click()
time.sleep(5)
driver.find_element(By.XPATH, '/html/body/div[1]/div/div/div[1]/div[1]/div[3]/a').click()
time.sleep(5)
driver.find_element(By.XPATH, '/html/body/div[1]/div/div/div[2]/div/div[2]/button[2]').click()
time.sleep(5)
driver.find_element(By.XPATH, '/html/body/div[1]/div/div/div[2]/div/form/div[1]/div[1]/input').send_keys("Grace")
time.sleep(10)
driver.find_element(By.XPATH, '/html/body/div[1]/div/div/div[2]/div/form/div[1]/div[2]/input').send_keys("uko")
time.sleep(10)
driver.find_element(By.XPATH, '/html/body/div[1]/div/div/div[2]/div/form/div[1]/div[3]/input').send_keys("100232")
time.sleep(5)
driver.find_element(By.XPATH, '/html/body/div[1]/div/div/div[2]/div/form/div[2]/input').click()
time.sleep(5)
driver.find_element(By.XPATH, '/html/body/div[1]/div/div/div[2]/div/div[2]/div[9]/button[2]').click()
driver.quit()
